/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class BaseElement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BaseElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BaseElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_BaseElement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AdaptiveCardObjectModelJNI.BaseElement_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AdaptiveCardObjectModelJNI.BaseElement_change_ownership(this, swigCPtr, true);
  }

  // check if the C++ code finds an object and just return ourselves if it doesn't
  public BaseElement findImplObj() {
     Object o = swigOriginalObject();
     return o != null ? (BaseElement)o : this;
  }

  public BaseElement() {
    this(AdaptiveCardObjectModelJNI.new_BaseElement__SWIG_0(), true);
    AdaptiveCardObjectModelJNI.BaseElement_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public BaseElement(BaseElement arg0) {
    this(AdaptiveCardObjectModelJNI.new_BaseElement__SWIG_1(BaseElement.getCPtr(arg0), arg0), true);
    AdaptiveCardObjectModelJNI.BaseElement_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public String GetElementTypeString() {
    return AdaptiveCardObjectModelJNI.BaseElement_GetElementTypeString(swigCPtr, this);
  }

  public void SetElementTypeString(String value) {
    AdaptiveCardObjectModelJNI.BaseElement_SetElementTypeString(swigCPtr, this, value);
  }

  public String GetId() {
    return (getClass() == BaseElement.class) ? AdaptiveCardObjectModelJNI.BaseElement_GetId(swigCPtr, this) : AdaptiveCardObjectModelJNI.BaseElement_GetIdSwigExplicitBaseElement(swigCPtr, this);
  }

  public void SetId(String value) {
    if (getClass() == BaseElement.class) AdaptiveCardObjectModelJNI.BaseElement_SetId(swigCPtr, this, value); else AdaptiveCardObjectModelJNI.BaseElement_SetIdSwigExplicitBaseElement(swigCPtr, this, value);
  }

  public long GetInternalId() {
    return AdaptiveCardObjectModelJNI.BaseElement_GetInternalId(swigCPtr, this);
  }

  public String Serialize() {
    return (getClass() == BaseElement.class) ? AdaptiveCardObjectModelJNI.BaseElement_Serialize(swigCPtr, this) : AdaptiveCardObjectModelJNI.BaseElement_SerializeSwigExplicitBaseElement(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue((getClass() == BaseElement.class) ? AdaptiveCardObjectModelJNI.BaseElement_SerializeToJsonValue(swigCPtr, this) : AdaptiveCardObjectModelJNI.BaseElement_SerializeToJsonValueSwigExplicitBaseElement(swigCPtr, this), true);
  }

  public JsonValue GetAdditionalProperties() {
    return new JsonValue(AdaptiveCardObjectModelJNI.BaseElement_GetAdditionalProperties(swigCPtr, this), true);
  }

  public void SetAdditionalProperties(JsonValue additionalProperties) {
    AdaptiveCardObjectModelJNI.BaseElement_SetAdditionalProperties(swigCPtr, this, JsonValue.getCPtr(additionalProperties), additionalProperties);
  }

  public FallbackType GetFallbackType() {
    return FallbackType.swigToEnum(AdaptiveCardObjectModelJNI.BaseElement_GetFallbackType(swigCPtr, this));
  }

  public boolean MeetsRequirements(SWIGTYPE_p_std__unordered_mapT_std__string_std__string_t arg0) {
    return AdaptiveCardObjectModelJNI.BaseElement_MeetsRequirements(swigCPtr, this, SWIGTYPE_p_std__unordered_mapT_std__string_std__string_t.getCPtr(arg0));
  }

  public BaseElement GetFallbackContent() {
    long cPtr = AdaptiveCardObjectModelJNI.BaseElement_GetFallbackContent(swigCPtr, this);
    return (cPtr == 0) ? null : new BaseElement(cPtr, true);
  }

  public void GetResourceInformation(RemoteResourceInformationVector resourceUris) {
    if (getClass() == BaseElement.class) AdaptiveCardObjectModelJNI.BaseElement_GetResourceInformation(swigCPtr, this, RemoteResourceInformationVector.getCPtr(resourceUris), resourceUris); else AdaptiveCardObjectModelJNI.BaseElement_GetResourceInformationSwigExplicitBaseElement(swigCPtr, this, RemoteResourceInformationVector.getCPtr(resourceUris), resourceUris);
  }

  public Object swigOriginalObject() {
    return AdaptiveCardObjectModelJNI.BaseElement_swigOriginalObject(swigCPtr, this);
  }

}
